version: '3'

networks:
    gateway:
        external: true
        driver: bridge

services:
    servicea:
        build:
            context: ./servicea
            dockerfile: Dockerfile
        image: node/app
        command: "npm run dev"
        ports:
            - "8081:8081"
        environment:
            - API_NAME="A"
            - PORT=":8081"
            - GATEWAY_HOST="http://gateway"
            - GATEWAY_PORT="3000"
            - GATEWAY_ROUTE_REGISTER="/register"
        volumes:
            - './servicea:/usr/app'
        networks:
            - gateway

    serviceb:
        build:
            context: ./serviceb
            dockerfile: Dockerfile
        image: node/app
        command: "npm run dev"
        ports:
            - "8082:8082"
        environment:
            - API_NAME='B'
            - PORT=':8082'
            - CONTENT="<h1>Service B</h1>"
        volumes:
            - './serviceb:/usr/app'
        networks:
            - gateway
